---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "pip-services-sms"
  description: "sms delivery microservice for pip-services"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

{{#if ELASTICSEARCH_LOGGING_ENABLED}}
# ElasticSearch logger
- descriptor: "pip-services:logger:elasticsearch:default:1.0"
  level: "info"
  connection:
    protocol: http
    host: {{ELASTICSEARCH_LOGGING_SERVICE_HOST}}
    port: {{ELASTICSEARCH_LOGGING_SERVICE_PORT}}
{{/if}}

# Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"
  level: "trace"

# Prometheus performance counters
{{#if PUSHGATEWAY_METRICS_ENABLED}}
- descriptor: "pip-services:counters:prometheus:default:1.0"
  level: "trace"
  interval: "30000"  
  connection:
    protocol: http
    host: {{PUSHGATEWAY_METRICS_SERVICE_HOST}}
    port: {{PUSHGATEWAY_METRICS_SERVICE_PORT}}
{{/if}}

# Default controller
- descriptor: "pip-services-sms:controller:default:default:1.0"
  connection:
    service: "{{{SMS_SERVICE}}}"
    host: "{{{SMS_SERVICE_HOST}}}"
    secure_connection: "{{{SMS_SSL}}}"
    port: "{{{SMS_SERVICE_PORT}}}"
  credential:
    username: "{{{SMS_USER}}}"
    password: "{{{SMS_PASS}}}"
  message:
    from: "{{{SMS_FROM}}}"
  parameters:
    client_name: "{{{CLIENT_NAME}}}"
    client_url: "{{{CLIENT_URL}}}"
    server_url: "{{{SERVER_URL}}}"
    signature: "{{{SMS_SIGNATURE}}}"
  options:
    magic_code: "{{{MAGIC_CODE}}}"
    verify_on_create: {{SMS_VALIDATE_ON_CREATE}}{{#unless SMS_VALIDATE_ON_CREATE}}true{{/unless}}
    verify_on_update: {{SMS_VALIDATE_ON_UPDATE}}{{#unless SMS_VALIDATE_ON_UPDATE}}true{{/unless}}

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# HTTP endpoint version 1.0
- descriptor: "pip-services-sms:service:http:default:1.0"

# Heartbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

# Prometheus metrics service
- descriptor: "pip-services:metrics-service:prometheus:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8082