---
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-smsdelivery:persistence:file:default:1.0"
  path: "./data/sms_settings.json"

- descriptor: "pip-services-smsdelivery:controller:default:default:1.0"
  message:
    from: 'somebody@somewhere.com'
    to: 'somebody@somewhere.com'
  parameters:
    company: 'My Company'
  connection:
    service: 'Gmail'
    host: 'smtp.gmail.com'
    secure_connection: true
    port: 465
  credential:
    username: 'somebody@gmail.com'
    password: 'pass123'
  options:
    magic_code: '123'
    verify_on_create: true
    verify_on_update: true

- descriptor: "pip-services-smsdelivery:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080
